version: "3.7"

services:
  web-app:
    build: 
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
      - 9000:80
    volumes:
      - './src:/var/www/myapp'
      - './src/config/php.ini:/var/www/etc/php/php.ini'
      - .:/app
      - /app/vendor
    depends_on:
      - redis

  web:
    image: nginx
    ports:
      - 80:80
    volumes:
      - './src:/var/www/myapp'
      - './src/config/site.conf:/var/www/etc/nginx/conf.d/site.conf'
    depends_on:
      - php

  php:
    image: php:7.2-fpm
    volumes:
      - ./src:/var/www/myapp
      - ./src/config/php.ini:/var/www/etc/php/php.ini
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  # composer:
  #   image: composer:1.9
  #   command: ["composer", "install"]
  #   volumes:
  #     - ./src:/app

  #===============#
  # install composer #
  #===============#
  composer:
    image: composer/composer
    volumes:
      - .:/app
    working_dir: /app    
    command: install

volumes:
  redis-data:
