version: '3.7'

services:
  app-gw:
    #image: nginx:latest
    build: 
      context: .
      dockerfile: './docker/nginx/Dockerfile'
    ports:
      - 80:80
    volumes:
      # - './config/default.conf:/usr/local/etc/nginx/conf.d/default.conf'
      - '.:/usr/share/nginx/html'
    env_file:
      - '.env'
    depends_on:
      - 'web'
    links:
      - 'web'

  web:
    build: 
      context: .
      dockerfile: './docker/php/Dockerfile'
    ports:
      - '9000:9000'
      - '9001:80'
    expose:
      - 9000
      - 9001
    volumes:
      # - './config/php-dev.ini:/usr/local/etc/php/conf.d/php-dev.ini'
      - '.:/usr/share/nginx/html'
    env_file:
      - '.env'
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

volumes:
  redis-data: